// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSudoku_v0._0._7.Data;

#nullable disable

namespace WebSudoku_v0._0._7.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250513030823_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebSudoku_v0._0._7.Models.DtoSudokuPuzzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoardValues")
                        .IsRequired()
                        .HasMaxLength(81)
                        .HasColumnType("nvarchar(81)")
                        .HasAnnotation("Relational:JsonPropertyName", "boardValues");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "difficulty");

                    b.HasKey("Id")
                        .HasName("PK_SudokuPuzzle");

                    b.ToTable("SudokuPuzzles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
